### ISSUE TITLE
Problem about game in fullscreen

### ISSUE THREAD

**Issue by giannigiorgi** [DanielBakovic/MyArcadePlugin#1]
Hi Daniel,

I have a problem with iframe games. They don't show in fullscreen even if I set 100% in width and height settings. An example is http://slotonlineaams.com/giochi/fowl-play-gold/
Can you help me? The theme is Gameleon for wordpress.

**Comment by DanielBakovic** [comment]
Hi,
I'll check the issue.

**Comment by DanielBakovic** [comment]
should be fixed now.
